OWNERS: Adding yasminvalim to approvers
openshift/os pull request #1333
Opened 2023-07-19 15:37 UTC by yasminvalim

As part of the onboarding process, it is necessary to add the Github user to the OWNERS file.

2023-07-19 16:02 UTC, ravanelli commented on OWNERS
> +  - yasminvalim
Weird, doesn't seems something git is adding in the diff

2023-07-19 17:54 UTC, mike-nguyen commented on OWNERS
> +  - yasminvalim
It's an extra newline at the end of the file. Just remove it so -yaminvalim is the last line.

2023-07-19 18:18 UTC, ravanelli commented on OWNERS
> +  - yasminvalim
It is her editor (vscode) that is adding it by default:

```
-  - lukewarmtemp
\ No newline at end of file
+  - lukewarmtemp
+  - yasminvalim
\ No newline at end of file

```
My diff
```
diff --git a/OWNERS b/OWNERS
index 0c13df2..48d9cd5 100644
--- a/OWNERS
+++ b/OWNERS
@@ -30,3 +30,4 @@ approvers:
   - cverna
   - Adam0Brien
   - lukewarmtemp
+  - yasminvalim
```
She is fixing it

2023-07-19 19:12 UTC, yasminvalim commented on OWNERS
> +  - yasminvalim
It was my editor! Fixed my Git and VSCode local settings! 
 I reverted the initial commit and redid the changes. 
 I believe it's without the warning now. 
 Thank you! :sparkles:

2023-07-19 19:19 UTC, marmijo reviewed
We usually only commit what will land in the code instead of small changes along the way. Mind changing this to only the original commit? :smile:

2023-07-20 15:19 UTC, ravanelli requested changes

2023-07-20 16:18 UTC, closed without merging