Add initial C10S variant
openshift/os pull request #1498
Opened 2024-04-30 16:05 UTC by travier

c9s: Point image-c9s to image-rhel-9.4

---

c9s: Use RPMs from 9.4 RHAOS repo

---

Revert "c9s.repo: temporarily use mirrored repos"

This reverts commit 88e41a0fef0dbe8e0b2d103cadd37217c8cd0933.

---

DoNotMerge: CI changes to test C10S builds

---

manifests: Add initial c10s based variant

See: https://github.com/openshift/os/issues/1466

---

kola-denylist.yaml: Update for c10s variant

---

c10s.repo: Skip GPG checks for now

2024-04-30 16:06 UTC, travier commented
Do not merge as it includes changes that we do not want but that are here to test in CI (see commits).
We'll have to update the Prow CI config once ready.
/hold

2024-05-06 09:52 UTC, travier commented
/retest

2024-05-06 17:52 UTC, jlebon commented
Hmm, almost seems like the logs are truncated... This is probably fallout from https://github.com/coreos/coreos-assembler/pull/3785.

2024-05-06 18:21 UTC, jlebon commented
Let's see if https://github.com/coreos/coreos-assembler/pull/3792 helps (then here, we'd `export TAIL_SLEEP=3` or something).

2024-05-07 03:21 UTC, jlebon commented
/retest

2024-05-07 03:35 UTC, jlebon commented
Ahh and indeed now we clearly see the error for all of them which means we were missing output. Yuck OK, so we need to fix the `tail` handling. Though I'll see if I can bang on the virtio-serial bug again.

2024-05-07 08:50 UTC, travier commented
> Ahh and indeed now we clearly see the error for all of them which means we were missing output. Yuck OK, so we need to fix the `tail` handling. Though I'll see if I can bang on the virtio-serial bug again.

Thanks! I indeed had a missing change in those commits.

2024-05-07 08:53 UTC, travier commented
Hum, the workaround is not that ugly and only impacts CI here so maybe we should merge it for now until we've fixed this COSA.

2024-05-07 09:48 UTC, travier commented
CI fixes in https://github.com/openshift/release/pull/51750

2024-05-07 18:24 UTC, jlebon commented
> and only impacts CI here

So far. :) It's racy so I don't see why it couldn't happen in the prod pipeline. I'd hate for someone to be debugging a failure there and working with incomplete output thinking the error is happening somewhere other than it really is.

I guess though a major hack is to just add a `sleep 1` at least on the cosa side.

2024-05-13 16:06 UTC, travier commented
Failing on missing the teamd package.

2024-05-13 16:12 UTC, travier commented
https://github.com/coreos/fedora-coreos-tracker/issues/1727

2024-05-14 10:33 UTC, travier commented
/retest

2024-05-14 12:53 UTC, travier commented
kdump not working:
```
systemctl status kola-runext.service:
× kola-runext.service
     Loaded: loaded (/etc/systemd/system/kola-runext.service; static)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: failed (Result: exit-code) since Tue 2024-05-14 12:01:37 UTC; 207ms ago
   Duration: 79ms
    Process: 2200 ExecStart=/usr/local/bin/kola-runext-test.sh (code=exited, status=1/FAILURE)
   Main PID: 2200 (code=exited, status=1/FAILURE)
        CPU: 27ms

May 14 12:01:36 qemu0 systemd[1]: Started kola-runext.service.
May 14 12:01:36 qemu0 kola-runext-test.sh[2200]: + . /var/opt/kola/extdata/commonlib.sh
May 14 12:01:36 qemu0 kola-runext-test.sh[2200]: ++ IFS=' '
May 14 12:01:36 qemu0 kola-runext-test.sh[2200]: ++ read -r -a cmdline
May 14 12:01:36 qemu0 kola-runext-test.sh[2200]: + case "${AUTOPKGTEST_REBOOT_MARK:-}" in
May 14 12:01:36 qemu0 kola-runext-test.sh[2200]: + is_service_active kdump.service
May 14 12:01:36 qemu0 kola-runext-test.sh[2200]: + local service=kdump.service
May 14 12:01:36 qemu0 kola-runext-test.sh[2200]: + for _x in {0..60}
May 14 12:01:36 qemu0 kola-runext-test.sh[2201]: ++ systemctl is-active kdump.service
May 14 12:01:37 qemu0 kola-runext-test.sh[2200]: + '[' inactive '!=' activating ']'
May 14 12:01:37 qemu0 kola-runext-test.sh[2200]: + break
May 14 12:01:37 qemu0 kola-runext-test.sh[2200]: + systemctl is-active kdump.service
May 14 12:01:37 qemu0 kola-runext-test.sh[2202]: inactive
May 14 12:01:37 qemu0 kola-runext-test.sh[2200]: + fatal 'kdump.service failed to start'
May 14 12:01:37 qemu0 kola-runext-test.sh[2200]: + echo 'kdump.service failed to start'
May 14 12:01:37 qemu0 kola-runext-test.sh[2200]: kdump.service failed to start
May 14 12:01:37 qemu0 kola-runext-test.sh[2200]: + exit 1
May 14 12:01:37 qemu0 systemd[1]: kola-runext.service: Main process exited, code=exited, status=1/FAILURE
May 14 12:01:37 qemu0 systemd[1]: kola-runext.service: Failed with result 'exit-code'.
--- [31mFAIL[0m: ext.config.shared.kdump.crash (101.06s)
        cluster.go:162: Error: Unit kola-runext.service exited with code 1
        cluster.go:162: 2024-05-14T12:01:37Z cli: Unit kola-runext.service exited with code 1
        harness.go:1263: kolet failed: : kolet run-test-unit failed: Process exited with status 1
```

teamd test not working (expected as we removed team support):
```
systemctl status kola-runext.service:
× kola-runext.service
     Loaded: loaded (/etc/systemd/system/kola-runext.service; static)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: failed (Result: exit-code) since Tue 2024-05-14 12:02:35 UTC; 195ms ago
   Duration: 66ms
    Process: 2164 ExecStart=/usr/local/bin/kola-runext-test.sh (code=exited, status=1/FAILURE)
   Main PID: 2164 (code=exited, status=1/FAILURE)
        CPU: 20ms

May 14 12:02:35 qemu0 systemd[1]: Started kola-runext.service.
May 14 12:02:35 qemu0 kola-runext-test.sh[2164]: + . /var/opt/kola/extdata/commonlib.sh
May 14 12:02:35 qemu0 kola-runext-test.sh[2164]: ++ IFS=' '
May 14 12:02:35 qemu0 kola-runext-test.sh[2164]: ++ read -r -a cmdline
May 14 12:02:35 qemu0 kola-runext-test.sh[2164]: + team=team0
May 14 12:02:35 qemu0 kola-runext-test.sh[2165]: ++ get_ipv4_for_nic team0
May 14 12:02:35 qemu0 kola-runext-test.sh[2165]: ++ local nic_name=team0
May 14 12:02:35 qemu0 kola-runext-test.sh[2165]: ++ local ip
May 14 12:02:35 qemu0 kola-runext-test.sh[2167]: +++ ip -j addr show team0
May 14 12:02:35 qemu0 kola-runext-test.sh[2168]: +++ jq -r '.[0].addr_info | map(select(.family == "inet")) | .[0].local'
May 14 12:02:35 qemu0 kola-runext-test.sh[2167]: Device "team0" does not exist.
May 14 12:02:35 qemu0 kola-runext-test.sh[2165]: ++ ip=
May 14 12:02:35 qemu0 kola-runext-test.sh[2165]: ++ '[' -z '' ']'
May 14 12:02:35 qemu0 kola-runext-test.sh[2165]: ++ echo 'Error: can not get ip for team0'
May 14 12:02:35 qemu0 kola-runext-test.sh[2165]: ++ exit 1
May 14 12:02:35 qemu0 kola-runext-test.sh[2164]: + nic_ip='Error: can not get ip for team0'
May 14 12:02:35 qemu0 systemd[1]: kola-runext.service: Main process exited, code=exited, status=1/FAILURE
May 14 12:02:35 qemu0 systemd[1]: kola-runext.service: Failed with result 'exit-code'.
--- [31mFAIL[0m: ext.config.shared.networking.team-dhcp-via-ignition (59.40s)
        cluster.go:162: Error: Unit kola-runext.service exited with code 1
        cluster.go:162: 2024-05-14T12:02:35Z cli: Unit kola-runext.service exited with code 1
        harness.go:1263: kolet failed: : kolet run-test-unit failed: Process exited with status 1
```

No more ifcfg files:
```
=== RUN   non-exclusive-test-bucket-0/ext.config.shared.networking.nm-ifcfg-rh-plugin
systemctl status kola-runext-63.service:
× kola-runext-63.service
     Loaded: loaded (/etc/systemd/system/kola-runext-63.service; static)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: failed (Result: exit-code) since Tue 2024-05-14 12:24:42 UTC; 248ms ago
   Duration: 59ms
    Process: 5657 ExecStart=/usr/local/bin/kola-runext-nm-ifcfg-rh-plugin (code=exited, status=1/FAILURE)
   Main PID: 5657 (code=exited, status=1/FAILURE)
        CPU: 21ms

May 14 12:24:42 qemu0 kola-runext-nm-ifcfg-rh-plugin[5657]: ++ DOCUMENTATION_URL=https://docs.okd.io/latest/welcome/index.html
May 14 12:24:42 qemu0 kola-runext-nm-ifcfg-rh-plugin[5657]: ++ BUG_REPORT_URL=https://access.redhat.com/labs/rhir/
May 14 12:24:42 qemu0 kola-runext-nm-ifcfg-rh-plugin[5657]: ++ REDHAT_BUGZILLA_PRODUCT='OpenShift Container Platform'
May 14 12:24:42 qemu0 kola-runext-nm-ifcfg-rh-plugin[5657]: ++ REDHAT_BUGZILLA_PRODUCT_VERSION=4.16
May 14 12:24:42 qemu0 kola-runext-nm-ifcfg-rh-plugin[5657]: ++ REDHAT_SUPPORT_PRODUCT='OpenShift Container Platform'
May 14 12:24:42 qemu0 kola-runext-nm-ifcfg-rh-plugin[5657]: ++ REDHAT_SUPPORT_PRODUCT_VERSION=4.16
May 14 12:24:42 qemu0 kola-runext-nm-ifcfg-rh-plugin[5657]: ++ OPENSHIFT_VERSION=4.16
May 14 12:24:42 qemu0 kola-runext-nm-ifcfg-rh-plugin[5657]: ++ OSTREE_VERSION=416.10.202405141044-0
May 14 12:24:42 qemu0 kola-runext-nm-ifcfg-rh-plugin[5657]: + '[' scos == rhcos ']'
May 14 12:24:42 qemu0 kola-runext-nm-ifcfg-rh-plugin[5657]: + is_scos
May 14 12:24:42 qemu0 kola-runext-nm-ifcfg-rh-plugin[5657]: + source /etc/os-release
May 14 12:24:42 qemu0 kola-runext-nm-ifcfg-rh-plugin[5657]: ++ NAME='CentOS Stream CoreOS'
May 14 12:24:42 qemu0 kola-runext-nm-ifcfg-rh-plugin[5657]: ++ ID=scos
May 14 12:24:42 qemu0 kola-runext-nm-ifcfg-rh-plugin[5657]: ++ ID_LIKE='rhel fedora'
May 14 12:24:42 qemu0 kola-runext-nm-ifcfg-rh-plugin[5657]: ++ VERSION=416.10.202405141044-0
May 14 12:24:42 qemu0 kola-runext-nm-ifcfg-rh-plugin[5657]: ++ VERSION_ID=4.16
May 14 12:24:42 qemu0 kola-runext-nm-ifcfg-rh-plugin[5657]: ++ VARIANT=CoreOS
May 14 12:24:42 qemu0 kola-runext-nm-ifcfg-rh-plugin[5657]: ++ VARIANT_ID=coreos
May 14 12:24:42 qemu0 kola-runext-nm-ifcfg-rh-plugin[5657]: ++ PLATFORM_ID=platform:el10
May 14 12:24:42 qemu0 kola-runext-nm-ifcfg-rh-plugin[5657]: ++ PRETTY_NAME='CentOS Stream CoreOS 416.10.202405141044-0'
May 14 12:24:42 qemu0 kola-runext-nm-ifcfg-rh-plugin[5657]: ++ ANSI_COLOR='0;31'
May 14 12:24:42 qemu0 kola-runext-nm-ifcfg-rh-plugin[5657]: ++ CPE_NAME=cpe:/o:centos:centos:10::coreos
May 14 12:24:42 qemu0 kola-runext-nm-ifcfg-rh-plugin[5657]: ++ HOME_URL=https://centos.org/
May 14 12:24:42 qemu0 kola-runext-nm-ifcfg-rh-plugin[5657]: ++ DOCUMENTATION_URL=https://docs.okd.io/latest/welcome/index.html
May 14 12:24:42 qemu0 kola-runext-nm-ifcfg-rh-plugin[5657]: ++ BUG_REPORT_URL=https://access.redhat.com/labs/rhir/
May 14 12:24:42 qemu0 kola-runext-nm-ifcfg-rh-plugin[5657]: ++ REDHAT_BUGZILLA_PRODUCT='OpenShift Container Platform'
May 14 12:24:42 qemu0 kola-runext-nm-ifcfg-rh-plugin[5657]: ++ REDHAT_BUGZILLA_PRODUCT_VERSION=4.16
May 14 12:24:42 qemu0 kola-runext-nm-ifcfg-rh-plugin[5657]: ++ REDHAT_SUPPORT_PRODUCT='OpenShift Container Platform'
May 14 12:24:42 qemu0 kola-runext-nm-ifcfg-rh [...]

2024-05-14 16:39 UTC, travier commented
```
Installing packages: Packages not found: amd-gpu-firmware, intel-gpu-firmware, nvidia-gpu-firmware
```

2024-05-14 16:47 UTC, travier commented
https://issues.redhat.com/browse/RHEL-36319

2024-05-23 13:26 UTC, travier commented
```
    --- [31mFAIL[0m: non-exclusive-test-bucket-0/ext.config.shared.podman.dns (180.51s)
            harness.go:106: TIMEOUT[3m0s]: ssh: sudo ./kolet run-test-unit --deny-reboots kola-runext-69.service
            harness.go:106: TIMEOUT[3m0s]: ssh: journalctl -t kola-runext-test.sh
```

```
    --- [31mFAIL[0m: non-exclusive-test-bucket-0/ext.config.shared.podman.rootless-pasta-networking (180.48s)
            harness.go:106: TIMEOUT[3m0s]: ssh: sudo ./kolet run-test-unit --deny-reboots kola-runext-70.service
            harness.go:106: TIMEOUT[3m0s]: ssh: journalctl -t kola-runext-rootless-pasta-networking
```

```
2024-05-23T09:56:53Z kola: Test timed out. Adding as candidate for rerun success: ext.config.shared.podman.rootless-systemd
--- [31mFAIL[0m: ext.config.shared.podman.rootless-systemd (904.79s)
        harness.go:106: TIMEOUT[15m0s]: ssh: sudo ./kolet run-test-unit kola-runext.service
        harness.go:106: TIMEOUT[15m0s]: ssh: journalctl -t kola-runext-rootless-systemd
```

2024-06-06 06:15 UTC, travier commented
```
error: Installing packages: Could not depsolve transaction; 1 problem detected:
 Problem: conflicting requests
  - nothing provides containernetworking-plugins >= 0.8.2-3 needed by cri-o-1.28.6-7.rhaos4.15.git70c2e96.el9.x86_64 from rhel-9.4-server-ose-4.17
  - nothing provides containernetworking-plugins >= 0.8.2-3 needed by cri-o-1.29.4-6.rhaos4.16.git0e93ae2.el9.x86_64 from rhel-9.4-server-ose-4.17
failed to execute cmd-fetch: exit status 1
```

We'll need new cri-o builds to move forward.

2024-06-06 21:56 UTC, LorbusChris commented on c10s.repo
> +# baseurl=https://mirror.stream.centos.org/SIGs/10-stream/cloud/$basearch/okd-4.15/
```suggestion
# baseurl=https://mirror.stream.centos.org/SIGs/10-stream/cloud/$basearch/okd-4.17/
```
This repo doesn't exist yet, but let's point it at 4.17 already. I'll set up the repo in the coming days.

2024-08-28 13:02 UTC, travier commented
We'll need the prep work for https://github.com/coreos/fedora-coreos-tracker/issues/1787 as well

2024-12-05 15:11 UTC, jlebon commented
Note we should also add a `rhel-10.0` variant as part of this.

2025-02-17 20:45 UTC, dustymabe commented on common-el9.yaml
I'm not opposed to the `common-el9.yaml` name here, but I think we should make an initial commit first that renames `manifest-el9-shared.yaml -> common-el9.yaml` and then add new changes to it.

2025-02-17 20:45 UTC, dustymabe commented on common.yaml
> +      - common-el9.yaml
neat trick. didn't know you could specify multiple to include..

2025-02-17 20:45 UTC, dustymabe commented on extensions/Dockerfile
> +RUN if rpm -q centos-stream-release; then \
Can we use the `RUN << EOF` pattern here instead of having the line continuation character `\` on each line?

Might make things easier to read.

2025-02-17 20:45 UTC, dustymabe commented on extensions/Dockerfile
> -RUN if [[ -n "${VARIANT}" ]]; then MANIFEST="manifest-${VARIANT}.yaml"; EXTENSIONS="extensions-${VARIANT}.yaml"; else MANIFEST="manifest.yaml"; EXTENSIONS="extensions.yaml"; fi && rpm-ostree compose
+1 for breaking up this long line, but maybe we could also use the `RUN <<EOF` model here too?

2025-02-17 20:45 UTC, dustymabe commented on extensions-c10s.yaml
worth pointing out there is no `extensions-c9s.yaml` - maybe we want to match was is being done for c9s with the naming here?

OR this is a better scheme and we want to change c9s to match.

2025-02-17 20:45 UTC, dustymabe commented on extensions-c10s.yaml
> +      - kernel-64k-modules-extra
should sysstat be down here? it's in the c9s one.

2025-02-17 20:45 UTC, dustymabe commented on manifest-c10s.yaml
> +rojig:
```suggestion
metadata:
```

2025-02-17 20:45 UTC, dustymabe commented on manifest-c10s.yaml
> +automatic-version-prefix: "10.<date:%Y%m%d%H%M>"
```suggestion
automatic-version-prefix: "10.0.<date:%Y%m%d>"
```

2025-02-17 20:45 UTC, dustymabe commented on manifest-c10s.yaml
> +# compose ID.
Is this still true? otherwise let's delete the comment

2025-02-17 20:45 UTC, dustymabe commented on manifest-ocp-rhel-10.0.yaml
In the new world where we are building node images as layered image builds on top of base image builds is this manifest needed? Or rather we'd just need a Dockerfile to feed into a container build?

2025-02-17 20:45 UTC, dustymabe commented on manifest-okd-c10s.yaml
> +rojig:
metadata

2025-02-17 20:45 UTC, dustymabe commented on manifest-okd-c10s.yaml
> +# Manifest for OKD node based on CentOS Stream CoreOS 1à
```suggestion
# Manifest for OKD node based on CentOS Stream CoreOS 10
```

2025-02-17 20:45 UTC, dustymabe commented on manifest-okd-c10s.yaml
> +  - rhel-9.6-appstream
temporary?

2025-02-18 09:47 UTC, jbtrystram commented
/retest

2025-02-18 09:57 UTC, travier commented on extensions/Dockerfile
> +RUN if rpm -q centos-stream-release; then \
I asked myself that as well but I don't know which version of podman/buildah added support thus I don't know if we have that in Prow.

2025-02-18 09:58 UTC, travier commented on common-el9.yaml
Hum, not sure I follow, the common manifest is from openshift/os and the shared one is from f-c-c so we can not merge those.

2025-02-18 13:05 UTC, jbtrystram commented on manifest-ocp-rhel-10.0.yaml
I think we want a manifest and use https://github.com/coreos/rpm-ostree/pull/5274

2025-02-18 19:54 UTC, dustymabe commented on manifest-ocp-rhel-10.0.yaml
but that would happen inside a container build, correct?

2025-02-18 19:58 UTC, dustymabe commented on extensions/Dockerfile
> +RUN if rpm -q centos-stream-release; then \
looks like https://github.com/containers/buildah/pull/5092 landed at the end of 2023

2025-02-18 19:58 UTC, dustymabe commented on extensions/Dockerfile
> +RUN if rpm -q centos-stream-release; then \
The CI run on this PR would tell us if it had it or not wouldn't it?

2025-02-18 20:00 UTC, dustymabe commented on common-el9.yaml
No. `fedora-coreos-config/manifests/shared-el9.yaml` and `manifest-el9-shared.yaml` are different. See https://github.com/openshift/os/commit/2210eccd87141d98ec7cef88cb07319a1e198f51

2025-02-19 01:44 UTC, HuijingHei commented
/retest

2025-02-19 10:22 UTC, travier commented on extensions-c10s.yaml
I fixed the name

2025-02-19 10:23 UTC, travier commented on extensions/Dockerfile
> +RUN if rpm -q centos-stream-release; then \
true

2025-02-19 10:25 UTC, jbtrystram commented on manifest-ocp-rhel-10.0.yaml
at some point yes, but we need https://issues.redhat.com/browse/COS-3024 first

2025-02-19 10:26 UTC, travier commented on common-el9.yaml
Ah, my bad this got introduced recently so I had missed those during the rebase

2025-02-19 13:25 UTC, dustymabe commented on manifest-c10s.yaml
> +automatic-version-prefix: "10.<date:%Y%m%d%H%M>"
Compare this with what we are doing for c9s. @jlebon chose 9.0.<date> intentionally.

2025-02-19 13:39 UTC, travier commented
Needs https://github.com/coreos/fedora-coreos-config/pull/3367.

2025-02-19 14:00 UTC, dustymabe commented on manifest-okd-c10s.yaml
> + # - centos-release-virt-common
Add comment on why these are commented out?

2025-02-19 14:33 UTC, travier commented on c10s.repo
> +gpgcheck=0
It's a leftover from when the c10s repos were not yet signed. Will remove

2025-02-19 16:39 UTC, travier commented on overlay.d/05rhcos/usr/lib/dracut/modules.d/50ignition-sgdisk/module-setup.sh
> +#!/bin/bash
Should go away with https://github.com/coreos/fedora-coreos-config/pull/3368

2025-02-19 21:55 UTC, dustymabe commented
CI failed with:

```
error: Installing packages: Unknown rpm-md repository: rhel-9.6-fast-datapath
```

2025-02-19 23:08 UTC, jbtrystram commented
> CI failed with:
> 
> ```
> error: Installing packages: Unknown rpm-md repository: rhel-9.6-fast-datapath
> ```
> 

Looking at the logs, [this]( https://github.com/openshift/os/commit/fa906886466489a19ae3d8aeb6d9e238ca5dffbb) doesn't work as expected maybe

2025-02-20 13:46 UTC, travier commented
Will rebase again now that we have https://github.com/openshift/os/pull/1752.

2025-02-20 13:55 UTC, travier commented on manifest-okd-c10s.yaml
> +  - rhel-9.6-appstream
yes, it's temporary until we have this published in the RHAOS repo or cri-o stops depending on it in the RHEL 10 if that's possible.

2025-02-20 13:57 UTC, travier commented on manifest-c10s.yaml
> +automatic-version-prefix: "10.<date:%Y%m%d%H%M>"
Hum, indeed., will do

2025-02-20 13:59 UTC, travier commented on extensions/Dockerfile
I think it was because all the repos for them were missing. Now we should be able to build some of them.

2025-02-20 13:59 UTC, travier commented on ci/get-ocp-repo.sh
> +# Get RHEL 9 repos for C10S builds for now
Once we have RHEL 10 / RHAOS 10 repos will all the needed packages.

2025-02-20 14:00 UTC, travier commented on extensions-okd-c10s.yaml
> +      - libreswan
Good question, we will have to ask the ipsec/telco folks.

2025-02-20 16:36 UTC, dustymabe commented
I think building the ISO here is going to fail until `coreos-installer` is updated. It currently is at `coreos-installer-0.22.1-2.el10.x86_64` in c10s so building the Live ISO will fail until we get `0.23+`.

2025-02-21 09:46 UTC, jbtrystram commented on ci/get-ocp-repo.sh
> +if [ "$osname" = scos ] && [ "${centos_version}" != "10" ]; then
for the okd-c10s variant `version` here evaluates to `419.96....` because in this specific case it's pulling the version from the default variant (see line 96 above). I pushed a fix. 

This script is hard to maintain :D

2025-02-21 11:30 UTC, jbtrystram commented on extensions-okd-c10s.yaml
> +      - rhel-10.0-appstream
we need the rhel10 repos to be mirrored in openshift for this to go through : https://github.com/openshift/release/pull/61812

2025-02-27 13:31 UTC, jbtrystram commented
/retest

2025-03-10 14:49 UTC, travier commented
I had pushed [`00a07bb` (#1498)](https://github.com/openshift/os/pull/1498/commits/00a07bbece76c8c57be0a46383db595f98a3c266) to try to fix this.

2025-03-21 14:37 UTC, jbtrystram commented
@travier regarding the last commit here to fix multipath, do you think we should make it into a el10-only manifest or an overlay is fine ?

2025-03-21 15:35 UTC, jlebon commented on README.md
> +- `okd-c9s`/`okd-c10s`: CentOS Stream-based CoreOS, including OpenShift
No need to add an `okd-c10s` variant. In fact, let's delete the `okd-c9s` variant.

2025-03-21 16:38 UTC, jbtrystram commented on README.md
> +- `okd-c9s`/`okd-c10s`: CentOS Stream-based CoreOS, including OpenShift
let's delete the okd-c9s variant in another PR

2025-03-24 09:31 UTC, jbtrystram commented
I messed up the last rebase here

2025-03-28 16:45 UTC, jlebon reviewed
Thanks all for working on this! A lot going on here. A bunch of commits here should be squashed together, others can be dropped. Can we add commit messages to the commits that have none?

I think to start, let's merge the smaller prep commits which don't directly introduce c10s-related manifests in a separate PR?

2025-03-28 16:45 UTC, jlebon commented on README.md
> +- `okd-c9s`/`okd-c10s`: CentOS Stream-based CoreOS, including OpenShift
https://github.com/openshift/os/pull/1780

2025-03-28 16:45 UTC, jlebon commented on README.md
> +- `okd-c9s`/`okd-c10s`: CentOS Stream-based CoreOS, including OpenShift
But still, let's not add `okd-c10s` in this PR.

2025-03-28 16:45 UTC, jlebon commented on extensions-okd-c10s.yaml
> +      - libreswan
https://github.com/openshift/os/pull/1771 will unpin it soon. Probably fine to not worry about this here for now.

2025-03-28 16:45 UTC, jlebon commented on image-okd-c10s.yaml
Nuke

2025-03-28 16:45 UTC, jlebon commented on manifest-okd-c10s.yaml
Nuke

2025-03-28 16:45 UTC, jlebon commented on oscontainer.yaml
Nuke this file. This is no longer needed since https://github.com/coreos/coreos-assembler/pull/3765.

2025-03-28 16:45 UTC, jlebon commented on extensions/Dockerfile
> +RUN --mount=type=secret,id=yumrepos,target=/os/secret.repo if [[ -n "${VARIANT}" ]]; then \
Or let's just switch it to [a heredoc](https://www.docker.com/blog/introduction-to-heredocs-in-dockerfiles/)? Not sure if the buildah in CI is new enough for it though, but could try.

2025-03-28 16:45 UTC, jlebon commented on ci/prow-entrypoint.sh
> +            kola_test_metal
Let's test the `c10s` variant instead.

2025-03-28 16:45 UTC, jlebon commented on ci/get-ocp-repo.sh
> +# If we are building the SCOS OKD 10 variant, then we need some RHEL packages for now.
The commit title says "Keep RHEL 9 repos", but we're keeping RHEL 10 repos, no?

2025-03-28 16:45 UTC, jlebon commented on overlay.d/22rhcos-mpathd/etc/multipath.conf
Let's just drop this commit. We shouldn't need it soon now that https://github.com/dracut-ng/dracut-ng/pull/1259 has merged. We can leave the multipath tests denylisted until it's backported.

2025-03-28 16:45 UTC, jlebon commented on ci/prow-entrypoint.sh
> +            cosa_init "c10s"
Nice. Had an earlier comment about that in the patch series. Should squash this commit into that earlier one.

2025-03-28 16:45 UTC, jlebon commented on ci/get-ocp-repo.sh
> +        variant="$(jq --raw-output '."coreos-assembler.config-variant"' < "$cosa_workdir"/src/config.json)"
Hmm, why?

2025-03-28 16:45 UTC, jlebon commented on ci/get-ocp-repo.sh
> +# Get RHEL 9 repos for C10S builds for now
Let's mention the packages we still need here, or ideally file an issue with the details and link to that here?

2025-03-28 16:45 UTC, jlebon commented on tests/kola/rpm-ostree/replace-rt-kernel/test.sh
> +            runv rpm-ostree override remove kernel{,-core} "${args[@]}"
Hmm, we shouldn't mix and match between kernel and kernel-rt packages though.

Anyway, this is moot since it looks like iptables was fixed to do this properly recently: https://gitlab.com/redhat/centos-stream/rpms/iptables/-/commit/46e0fa580ca4dfa77d5a652b75d2ae286abadf77

So we should be able to drop this commit.

(But nice commit message regardless BTW!)

2025-03-31 14:46 UTC, jlebon commented
I've opened https://github.com/openshift/os/pull/1780 which cleans a lot of things up and should make landing this easier!

2025-04-02 11:31 UTC, jbtrystram commented on overlay.d/22rhcos-mpathd/etc/multipath.conf
I'm afraid it's going to be a while. I have a PR in cosa that was waiting on a dracut release to be packaged in fedora for 6 months... downstream packaging seems to be faster however.

hmm although I suppose we're not shipping those builds any time soon so it's probably ok to keep the tests denylisted

2025-04-03 10:13 UTC, jbtrystram commented
/retitle [COS-2902]:  Add C10S variant

2025-04-03 10:23 UTC, jcapiitao commented
The PR is currently rebased on top of https://github.com/openshift/os/pull/1780 which is not yet merged, so the tests will fail.
We cleaned up the history (some drop and squash commit) to include the latest comment.

2025-04-03 14:22 UTC, jbtrystram commented
COS-2902: Add C10S variant

2025-04-04 14:55 UTC, jcapiitao commented
Requires https://github.com/coreos/coreos-assembler/pull/4064

2025-04-04 16:06 UTC, jlebon approved these changes
Thank you for adding more context in the commits!

First commit says "aglusterfs-fusend" which I think is a typo.

Otherwise, this looks sane to me!

/approve

I'd add a `/lgtm` but this will need a rebase anyway for https://github.com/openshift/os/pull/1780.

2025-04-04 17:58 UTC, jbtrystram requested changes
A few denylist entries can probably be removed

2025-04-04 17:58 UTC, jbtrystram commented on extensions-okd-c10s.yaml
> +  #     - kata-containers
because the kata container package is not available in c10s yet

2025-04-04 17:58 UTC, jbtrystram commented on extensions-okd-c10s.yaml
> +      - sysstat
@jcapiitao ^

2025-04-04 17:58 UTC, jbtrystram commented on kola-denylist.yaml
> +    - c10s
This one should pass (tested on rhel10)

2025-04-04 17:58 UTC, jbtrystram commented on kola-denylist.yaml
> +    - c10s
This one should pass (tested on rhel10)

2025-04-04 17:58 UTC, jbtrystram commented on kola-denylist.yaml
> +    - c10s
This one should pass (tested on rhel10)

2025-04-04 18:39 UTC, jcapiitao commented
> Thank you for adding more context in the commits!
> 
> First commit says "aglusterfs-fusend" which I think is a typo.
> 
> Otherwise, this looks sane to me!
> 
> /approve
> 
> I'd add a `/lgtm` but this will need a rebase anyway for #1780.

alright, I fixed the typo

2025-04-04 18:40 UTC, jbtrystram commented on kola-denylist.yaml
> +    - c10s
Also fixed in https://github.com/coreos/fedora-coreos-config/pull/3434

2025-04-04 18:42 UTC, jcapiitao commented on tests/kola/rpm-ostree/replace-rt-kernel/test.sh
> +            runv rpm-ostree override remove kernel{,-core} "${args[@]}"
Indeed with iptables-1.8.11-8.el10 the test is ok :+1: 
Thank you for having dug down more on that

2025-04-04 18:44 UTC, jcapiitao commented on kola-denylist.yaml
> +    - c10s
Removed in [f71d5f9](https://github.com/openshift/os/pull/1498/commits/f71d5f9e4c5abdb9dfaf6946a95772e7bcedc1cc)

2025-04-04 18:44 UTC, jcapiitao commented on kola-denylist.yaml
> +    - c10s
Removed in https://github.com/openshift/os/pull/1498/commits/fc2ab86dee92ab13a5af6656e3f29e2d6186d495

2025-04-04 18:44 UTC, jcapiitao commented on kola-denylist.yaml
> +    - c10s
Removed in https://github.com/openshift/os/pull/1498/commits/fc2ab86dee92ab13a5af6656e3f29e2d6186d495

2025-04-04 18:45 UTC, jcapiitao commented on kola-denylist.yaml
> +    - c10s
Removed in https://github.com/openshift/os/pull/1498/commits/fc2ab86dee92ab13a5af6656e3f29e2d6186d495

2025-04-04 18:55 UTC, jbtrystram commented on kola-denylist.yaml
> +    - c10s
it still needs to be denylisted until the next f-c-c submodule bmp

2025-04-04 19:18 UTC, jbtrystram commented
/unhold

2025-04-04 20:59 UTC, Prashanth684 commented on extensions-okd-c9s.yaml
> -  - c9s-sig-virtualization
```
error: Packages not found: openvswitch3.5-ipsec
```
Looks like we need to add `c9s-sig-nfv` here

2025-04-04 21:06 UTC, Prashanth684 commented
will there be a way to switch between building c9s and c10s, or will we have a follow up moving to c10s (in packages-openshift.yaml  and other places) after this PR?

2025-04-04 23:50 UTC, dustymabe commented
I'm looking into the failures here.

2025-04-05 00:03 UTC, dustymabe commented on extensions-okd-c9s.yaml
> -  - c9s-sig-virtualization
Should be fixed now.

2025-04-05 00:04 UTC, dustymabe commented
Pushed up a few fixes.. still working on some other things.

2025-04-05 02:25 UTC, dustymabe commented
ok a few more fixes now. I think (hope) the only thing left failing is the okd-scos-images

2025-04-05 02:35 UTC, dustymabe commented
Please everyone refrain from pushing to this PR unless I ask you to do so.

2025-04-05 02:42 UTC, jlebon commented
> will there be a way to switch between building c9s and c10s, or will we have a follow up moving to c10s (in packages-openshift.yaml and other places) after this PR?

We'll maintain both c9s and c10s variants. The repos in `packages-openshift.yaml` should be adapted so it's conditional on the version as well as `centos` vs `rhel`.

2025-04-05 07:38 UTC, jbtrystram commented
/retitle COS-2902: Add C10s variant

2025-04-05 07:41 UTC, jbtrystram commented
/lgtm

2025-04-05 07:45 UTC, merged

2025-04-08 14:37 UTC, jcapiitao commented
> will there be a way to switch between building c9s and c10s, or will we have a follow up moving to c10s (in packages-openshift.yaml and other places) after this PR?

@Prashanth684 there is an on-going follow-up patch https://github.com/openshift/os/pull/1786 which implements what you are asking for (specially the commit https://github.com/openshift/os/pull/1786/commits/e6213566189af6602a5e6c3aa79390457e49b2f7)