NO-JIRA: Bump fedora-coreos-config
openshift/os pull request #1658
Opened 2024-11-28 17:27 UTC by jlebon

This is basically https://github.com/openshift/os/pull/1644 but with a commit added. Doing it this way instead of pushing to that PR directly because the bot will just nuke my changes if new commits land in f-c-c.

```
Adam Piasecki (1):
      denylist: add multipath.partition

Dusty Mabe (7):
      tests/kola: add SELinux systemd /var/cache exceptions in upgrade test
      Move to Fedora Linux 41
      denylist: drop kdump.crash.nfs and ext.config.boot.bootupd-validate
      overrides: drop graduated grub2-2.12-10.fc41 override
      07fix-selinux-labels: fix service ordering
      tests/kola: fix potential unbound variable error
      ci: use OSbuild to build metal/metal4k in one shot

HuijingHei (5):
      test: extend bootupd test to include testing adoption and updates
      denylist: deny `ext.config.boot.bootupd-validate` until we rollout F41
      tests/kola: remove dtb exceptions in upgrade test SELinux checks
      tests/upgrade: drop the rollback deployment on aarch64
      tests/bootupd-validate: skip checking BIOS on older bootupd

Jonathan Lebon (17):
      workflows/add-overrides: install python3-dnf
      Inherit from fedora-bootc's tier-x on Fedora 42+
      manifests: conditionalize duplicate manifests
      manifests: split system-configuration.yaml
      manifests: split networking-tools.yaml
      manifests: split user-experience.yaml
      manifests: hoist up bootable-rpm-ostree.yaml include
      manifests: move veritysetup request to ignition-and-ostree.yaml
      manifests: move bootc to bootable-rpm-ostree.yaml
      manifests: conditionalize bootable-rpm-ostree.yaml
      manifests: just disable systemd-firstboot, don't nuke
      manifests: split ignition-and-ostree.yaml
      manifests: split tier-x dupes into separate manifest
      workflows: add `bump-fedora-bootc` workflow
      manifests/tier-x: use readonly in repo config only
      workflows/remove-graduated-overrides: clone with submodule
      manifests/fedora-coreos: move from `rojig` to `metadata`

Joseph Marrero Corchado (1):
      manifest: Add bootc

Michael Armijo (1):
      denylist: remove fcos.internet and podman.workflow

Nikita Dubrovskii (3):
      dnf5: use 'setopt' to enable 'updates-testing' repo
      dnf5 builddep: drop '--spec' as it no longer exists
      coreos-secex-ignition-prepare: remount /usr rw if needed
```

2024-11-29 15:28 UTC, jlebon commented
I had to add a conditional here to make this conditional on c9s/el9.6. Once we shed 9.4 from this repo, we can drop the conditional stuff and the `inherit_tier_x` variable.

2024-11-29 16:07 UTC, c4rt0 approved these changes
/lgtm

2024-11-29 23:13 UTC, jlebon commented
/retest

2024-11-30 11:48 UTC, c4rt0 commented
/retest

2024-12-02 16:05 UTC, jlebon commented
Failure here is legit. Digging into it.

2024-12-02 20:10 UTC, jlebon commented
OK, filed https://gitlab.com/redhat/centos-stream/containers/bootc/-/issues/1169 and added a denylist entry for it.

2024-12-03 15:46 UTC, c4rt0 requested changes

2024-12-03 15:46 UTC, c4rt0 commented on kola-denylist.yaml
> +    - rhel-9.6
```suggestion
    - rhel-9.4
    - rhel-9.6
```

2024-12-03 15:46 UTC, c4rt0 commented on kola-denylist.yaml
> +    - rhel-9.6
I saw this failing also at [rhel-9.4](https://github.com/openshift/os/issues/1656)

2024-12-03 15:53 UTC, c4rt0 approved these changes
/lgtm

2024-12-03 18:39 UTC, merged

2024-12-04 15:32 UTC, jlebon commented
Just wanted to highlight this because it's currently buried in the details: with this PR, the variants `c9s`, `okd-c9s`, `rhel-9.6` and `ocp-rhel-9.6` all now inherit from tier-x also (via FCOS). This notably means that we now have composefs turned on there.